# Generated by Django 5.2.1 on 2025-07-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_leaves_next_month_user_leaves_available_next_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='leaves_available_next_month',
        ),
        migrations.RemoveField(
            model_name='user',
            name='leaves_available_this_month',
        ),
    ]
