# Generated by Django 5.2.1 on 2025-07-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_user_leaves_available_next_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leaves_available_next_month',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='user',
            name='leaves_available_this_month',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
