# Generated by Django 5.2.1 on 2025-07-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_total_absent_days_user_total_present_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_late_entries_this_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_working_days_in_month',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
