# Generated by Django 5.2.1 on 2025-07-10 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_total_late_entries_this_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_late_entries_this_month',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_working_days_in_month',
        ),
        migrations.AddField(
            model_name='user',
            name='total_leave_days_in_this_month',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='user',
            name='total_working_days_in_this_month',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_absent_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_present_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
