# Generated by Django 5.2.1 on 2025-07-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_user_total_late_entries_this_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_leave_days_in_this_month',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_working_days_in_this_month',
        ),
    ]
