# Generated by Django 5.2.1 on 2025-07-11 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_user_total_leave_days_in_this_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='leaves_available_next_month',
            field=models.DecimalField(decimal_places=1, default=4, max_digits=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='leaves_available_this_month',
            field=models.DecimalField(decimal_places=1, default=4, max_digits=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
