# Generated by Django 5.2.1 on 2025-07-11 06:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_user_leaves_available_next_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_leave_days_in_this_month',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
