# Generated by Django 5.2.1 on 2025-06-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='is_half_day',
        ),
    ]
