# Generated by Django 5.2.1 on 2025-07-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_end_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_start_half_day',
            field=models.BooleanField(default=False),
        ),
    ]
