# Using the dir() function:-
'''
dir() is a built-in function to list all the function names (or variable names) in a module.
The dir() function can be used on all modules, also the ones you create yourself.
'''

import math    # importing built-in module 'math'.
import pprint  # For pretty printing long lists

content = dir(math)  # content is a variable which store all the function and variable names in the module 'math'.

pprint.pprint(content)  # calling 'pprint' function of 'pprint' module
# Output:-
# ['__doc__',
#  '__loader__',
#  '__name__',
#  '__package__',
#  '__spec__',
#  'acos',
#  'acosh',
#  'asin',
#  'asinh',
#  'atan',
#  'atan2',
#  'atanh',
#  'cbrt',
#  'ceil',
#  'comb',
#  'copysign',
#  'cos',
#  'cosh',
#  'degrees',
#  'dist',
#  'e',
#  'erf',
#  'erfc',
#  'exp',
#  'exp2',
#  'expm1',
#  'fabs',
#  'factorial',
#  'floor',
#  'fma',
#  'fmod',
#  'frexp',
#  'fsum',
#  'gamma',
#  'gcd',
#  'hypot',
#  'inf',
#  'isclose',
#  'isfinite',
#  'isinf',
#  'isnan',
#  'isqrt',
#  'lcm',
#  'ldexp',
#  'lgamma',
#  'log',
#  'log10',
#  'log1p',
#  'log2',
#  'modf',
#  'nan',
#  'nextafter',
#  'perm',
#  'pi',
#  'pow',
#  'prod',
#  'radians',
#  'remainder',
#  'sin',
#  'sinh',
#  'sqrt',
#  'sumprod',
#  'tan',
#  'tanh',
#  'tau',
#  'trunc',
#  'ulp']