# Generated by Django 5.2.1 on 2025-07-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_late',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave'), ('WEEKEND', 'Weekend')], default='ABSENT', max_length=10),
        ),
    ]
